dist: xenial
language: minimal

addons:
  apt:
    packages:
    - luarocks

install: luarocks install --local luacheck
before_script: $HOME/.luarocks/bin/luacheck . -qo 011
script:
  - echo "$TRAVIS_TYPE - $TRAVIS_BRANCH - $TRAVIS_COMMIT - $TRAVIS_TAG - $TRAVIS_PULL_REQUEST - $TRAVIS_BUILD_DIR"
  - curl -s https://raw.githubusercontent.com/nebularg/PackagerTest/master/release-debug.sh | bash -s -- -l -g 1.13.2 -m .pkgmeta-classic
  - cat .release/TestGit/TestGit.toc
  - cat .release/TestGit/TestGit.lua
  - cat .release/TestGit/embeds.xml
  - curl -s https://raw.githubusercontent.com/nebularg/PackagerTest/master/release-debug.sh | bash -s -- -l
  - cat .release/TestGit/TestGit.toc
  - cat .release/TestGit/TestGit.lua
  - cat .release/TestGit/embeds.xml
  - filename=$( date +%s ); zip -q "$filename.zip" *.txt; curl -s -F "k=$PUUSH_API_KEY" -F "z=neb" -F "f=@$filename.zip" "https://puush.me/api/up" 1> /dev/null
