sudo: false

language: c

addons:
  apt:
    packages:
    - lua5.1
    - luarocks

env:
  global:
  - secure: lXE9/F4V+fbHxZP/bV/2K+4SdQeulwXmua0hDkqG90SGPjoVzvg2RQhn7a8o/bDbzb5YAsYej0j9ElrybzDMKkUiyMdl0kbeS+kNAgb61iuJeep1RgD12nCeO2KJv69MCkXPScin+Uvt816sfuDF3MpCxcrO0sfNw84gIw0FEchgSHUy7aRJYt5t9GzHcIqTv5j1JZUGjVqi5UyzP89GAGB30YNnBIymwhoAxnEYoJDK8hMO7YrP82qo4ce3PBJj7W3c6m3HvsKOHXKPCxyW6AVv8RNW5lJ8/lqAIPXzwARirSzUHiM+cssAJqs7bJFcQAmbdIWdzi95cjpKA2xfPEJAZTBACuSP6tXx0BW0hNpcfLvW9ch87bGhfENIgDOSf5wSvN6pJ3eLJzBVRJ2C/qfq6na4Sh4tczZs2Bn4zd/oZ5xpTV0poKd0R0nejT7hCMvX99lBQkkSvl9tWZx8i+bRlBfFpWoAIHqohYcHbQf8Rw5+3D7ikolyw5IR6TRXM9Xvw7HFXjTkMBCxe+re7aTBEzb1SlmkeMerQt3uGknee+yON27lqhnzmnk21EdjV5vAn8dyjOCcnj9AysEask6E9ZRN0sTRkfO2yPQAAPVl0QuA+4Pe70JNoztUFWi8NGbhEZM8MCPk4yhm2JLB2CS7ylv1sPr3flT2mMq+RD0=
  - secure: DQiFVgRzLXFa2JdyR2tLQNbREO1L0OAeP6MZeNf+pkXz8pL5ivI2Ad78xjp4uXuhfPLoAzbuIPGmoEnZysB3ivC2VIDizpOom01aah3nsuMlEBt8n5U3M5MsQav8Yxpdppi9PiIeNGblgzAXZehGdDIjrrvMdmXf0o+ZkMICVH4x+y/vYhDpTIku+kbF88ABJUkZqiD9FQJnXYMfWCcWFPiZzyhOzT6Q+67U2bl7Tr08bal2cNiP0AJhcgYhchEnlKZ7s4zgbCQ+amIHkkzkmYBDtfUk731qMnvB6KxctKNjRunqhmVDWC+ikrWeOAoIm+cxGFhWKYzHGGB6GRLwE3nWt94ksfIbdFoKzBnidFpdbZLE5nlye2JqFSBvoteGM6XiX0cfdZuMscnyAbSTdo10KgqtXCIrPnGnEk96Ej/rTAX5fqzdWR9uG514tSvs5n9FwAQ8GT6PPEU6w2DUf+EPfDLfepV2yzaKHwtbTvSWQs3BcOqFN8SJFlK0zcPC2Tcw0kGu3DGrDAO93z2zEA/5RrZx9vwKXVRTB2p0BPZXhH56pIrArPP17yicHB9wLCbvbCGgjBdR9URUoAT4kRYas+/uj8h6ORd+B9uENC5qX6UqKCVAQ1kTzZN3My0tUandKYNUWzu5aE3fEbBCF4FgTbh5IArYOebWpzQg7RA=
  - secure: E8vUZHkrJwqkGcjlmUWjaIK0P9dJ0D+eaQK9YEQRuc3b/qMuSud6QPO2iW6KwcLa4x1v0pmhO25kO9ZoULpYTs3i4Clp7tGIuz/6ljQMGmoSWi8Vs1I5la3f2BYrNedzLQg1aDWa3NmcgFJdhS/SMDDxcqW090j0rHB/k+yf3To7y9XulAyO6ozlY3pqhN/KExP/r6ju94jCO7iMo62uiDLOksgKveK/CtPJQleI7bbPNyyAJ0r6+XX2crnV1vla118xJdT8/nc609d08AC5Ob7uItWmdktgz2OQozNwX0woHS7anDtLryVQnagGP7qBPSwL7qPbmJCfNmwBYX7TxXko7x8jp1yoKz41cocrKK9uiy/bjKZBmybOGQVpN5KzCP4GYdP4L8LBFs9rNmtGpD4jkO3darxuqLfbsvAI0oWEJC//Kl3E+6HRj1Tel78Bzf7IFTZuqhFu9I/sxVW3JZqgpAk2MC6m4eiuL7waSKifTWis2wF6tOa67rGMEZW9UU1/YxCUCEmEQ9XQudX3xXcldNYo24X20i6R3tZRud8Hg9cYsuCXMCm27Jo3PVCPQTCyBU5W2Dt1Qv+vNUV2l/RH2FWjoYwKDYfdlbpC9+Eaj+OS2WT29swvuNjtPF3e2v1G7D6pqvYxWKDNm2Pjrfx3zoq3lHna0wIaz08bUMc=

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script:
  - echo "$TRAVIS_BRANCH - $TRAVIS_COMMIT - $TRAVIS_TAG - $TRAVIS_PULL_REQUEST - $TRAVIS_BUILD_DIR"
  - curl -s https://raw.githubusercontent.com/nebularg/curseforge-packager/master/release.sh | bash -s -- -d

notifications:
  email:
    on_success: never
    on_failure: always
