name: build

on: push

env:
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: nebularg/actions-luacheck@master
      with:
        args: -o 011

    - name: Env check
      run: |
        echo "$GITHUB_EVENT_NAME - $GITHUB_REF - $GITHUB_SHA - $GITHUB_HEAD_REF - $GITHUB_WORKSPACE"
        jq . "$GITHUB_EVENT_PATH"

    - name: Package Retail
      uses: nebularg/packager@install-svn
      with:
        args: -l

    - name: Dump Retail
      run: |
        cat .release/TestGit/TestGit.toc
        cat .release/TestGit/TestGit.lua
        cat .release/TestGit/embeds.xml
