name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install dependancies
      run: |
        sudo apt-get install luarocks pandoc
        luarocks install --local luacheck

    - name: Run luacheck
      run: ~/.luarocks/bin/luacheck . -qo 011

    - name: Env check
      run: |
        echo "$GITHUB_EVENT_NAME - $GITHUB_REF - $GITHUB_SHA - $GITHUB_HEAD_REF - $GITHUB_WORKSPACE"
        jq . "$GITHUB_EVENT_PATH"

    - name: Package Classic
      uses: nebularg/packager@actionfun
      with:
        args: -l -g 1.13.2 -m .pkgmeta-classic

    - name: Dump Classic
      run: |
        cat .release/TestGit/TestGit.toc
        cat .release/TestGit/TestGit.lua
        cat .release/TestGit/embeds.xml

    - name: Package Retail
      uses: nebularg/packager@actionfun
      with:
        args: -l

    - name: Dump Retail
      run: |
        cat .release/TestGit/TestGit.toc
        cat .release/TestGit/TestGit.lua
        cat .release/TestGit/embeds.xml
